name: Test on PRs

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "*.toml"
    types: [opened, synchronize, reopened]

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "lts"
          - "1"
        os:
          - ubuntu-latest
        arch:
          - x64
        allow_failure: [false]
